apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
    - port: 443
      name: https
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  template:
    metadata:
      name: api
      labels:
        app: api
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: seniorsoftwarevlogger/reliability-api:latest
          imagePullPolicy: Never
          ports:
            - name: api
              containerPort: 3000
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            - name: PORT
              value: "3000"
            - name: SERVICES
              value: services/api.service.js
            - name: TRANSPORTER
              value: nats://nats:4222
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: someotherserviratingce
  labels:
    app.kubernetes.io/name: someotherservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: someotherservice
    spec:
      containers:
        - name: rating
          image: seniorsoftwarevlogger/reliability-rating:latest
          imagePullPolicy: Never
          env:
            - name: NODEID
              value: "node-someotherservice"
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            - name: SERVICES
              value: services/someother.service.js
            - name: TRANSPORTER
              value: nats://nats:4222
      restartPolicy: Always
