#########################################################
# Common Environment variables ConfigMap
#########################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
data:
  NAMESPACE: ""
  LOGLEVEL: info
  SERVICEDIR: services
  TRANSPORTER: nats://nats:4222

---
#########################################################
# Service for Moleculer API Gateway service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3030"
    filter.by.port.name: "true"
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics-prometheus
      targetPort: 3030
      port: 3030
      protocol: TCP
---
#########################################################
# Ingress for Moleculer API Gateway
#########################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000

---
#########################################################
# API Gateway service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ssv/reliability-services:idemp-fixed
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: api

---
#########################################################
# Greeter service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
spec:
  selector:
    matchLabels:
      app: tickets
  replicas: 1
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: ssv/reliability-services:idemp-fixed
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: tickets

---
#########################################################
# Conferences service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conferences
spec:
  selector:
    matchLabels:
      app: conferences
  replicas: 1
  template:
    metadata:
      labels:
        app: conferences
    spec:
      containers:
        - name: conferences
          image: ssv/reliability-services:idemp-fixed
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: conferences

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-conferences
spec:
  selector:
    matchLabels:
      app: db-conferences
  replicas: 1
  template:
    metadata:
      labels:
        app: db-conferences
    spec:
      containers:
        - name: db-conferences
          image: ssv/reliability-services:idemp-fixed
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: db-conferences

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tickets
spec:
  selector:
    matchLabels:
      app: db-tickets
  replicas: 1
  template:
    metadata:
      labels:
        app: db-tickets
    spec:
      containers:
        - name: db-tickets
          image: ssv/reliability-services:idemp-fixed
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: db-tickets
